<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_ContactorNonFB_ThermalRelay" Id="{6e03c52a-c6fa-4ea2-a467-73ac2fad92ac}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ContactorNonFB_ThermalRelay EXTENDS FB_ContactorNonFB IMPLEMENTS I_ActivePowerNoFB
VAR
	piFR		: FB_DigitalInput;
	bOverload	: BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[bOverload :=  piFR.In;]]></ST>
    </Implementation>
    <Property Name="IsOverload" Id="{d1f79765-5ea1-417c-ab92-3f7e5d28c481}">
      <Declaration><![CDATA[PROPERTY IsOverload : REFERENCE to bool]]></Declaration>
      <Get Name="Get" Id="{369760a0-3838-4cc3-b35f-2b8a00e21a41}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[isOverload ref= bOverload;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="Ref_piFR" Id="{d234bb82-4ae6-4d81-adbc-70191f4585c5}">
      <Declaration><![CDATA[PROPERTY Ref_piFR : reference to FB_DigitalInput]]></Declaration>
      <Get Name="Get" Id="{fde14fd9-1542-45b8-99cc-b7fc2cf0af94}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Ref_piFR ref= piFR;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <LineIds Name="FB_ContactorNonFB_ThermalRelay">
      <LineId Id="15" Count="0" />
    </LineIds>
    <LineIds Name="FB_ContactorNonFB_ThermalRelay.IsOverload.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_ContactorNonFB_ThermalRelay.Ref_piFR.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>