<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="POU" Id="{72876a34-3061-4895-8343-255626024a2e}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM POU
VAR
	FB_BurnerControlEcoFlam : FB_BurnerControlEcoFlam;
	FB_BurnerControlEcoFlamV2 : FB_BurnerControlEcoFlamV2;
	FB_BurnerControlEcoFlamV3 : FB_BurnerControlEcoFlamV3;
	FB_ContactorFBNO : FB_ContactorFBNO;
	fb_contactorNonFB : FB_ContactorNonFB;
	FB_Contactor1FB_ThermalRelay : FB_Contactor1FB_ThermalRelay;
	FB_ContactorNonFB_ThermalRelay : FB_ContactorNonFB_ThermalRelay;
	FB_ContactorNonFB_Flex_ThermalRelay : FB_ContactorNonFB_Flex_ThermalRelay;
	FB_SingleCoilCylinder : FB_SingleCoilCylinder;
	FB_DoubleCoilCylinder : FB_DoubleCoilCylinder;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="POU">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>