<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_SingleTankV01" Id="{89f4cc3f-74c6-42d0-a1e6-134d78a5c159}" SpecialFunc="None">
    <Declaration><![CDATA[(*
	FB_SingleTankV01 extends FB_SingleTankV0 with an additional cylinder (digital output) 
*)
FUNCTION_BLOCK FB_SingleTankV01 EXTENDS FB_SingleTankV0
VAR
	fbCylinderOut : FB_DigitalOutput;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Ref_CylinderOut" Id="{3eede384-d70f-4727-80f3-d34d2c5cf560}">
      <Declaration><![CDATA[PROPERTY Ref_CylinderOut : REFERENCE TO FB_DigitalOutput]]></Declaration>
      <Get Name="Get" Id="{5b97f124-4b14-4ea4-a79b-0efc1872d0a6}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Ref_CylinderOut ref= fbCylinderOut;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <LineIds Name="FB_SingleTankV01">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_SingleTankV01.Ref_CylinderOut.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>